version: '3.1'

services:

  usu:
    image: usu:0.24
    restart: always
    ports:
      - 8080:8080
    environment:
      HOSTNAME: dbb
      MYSQL_DATABASE: user
      MYSQL_USER: exampleus
      MYSQL_PASSWORD: rootpassworhgd
    depends_on:
      - dbb

  dbb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: user
      MYSQL_USER: exampleuseradd
      MYSQL_PASSWORD: rootpasswoeersd
      MYSQL_ROOT_PASSWORD: rootdpassword
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
