name: Docker/ARGO CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'Capstone-Project-work/**'   # Only trigger when changes happen in this directory

jobs:
  Build-Push-Docker:
        runs-on: ubuntu-latest
        steps:

        #BUILD STAGES
          - uses: actions/checkout@v4.2.1
            name: changing to the repo where the dockerfile is located

          - name: set up python
            uses: actions/setup-python@v2
            with: 
              python-version: 3.8


          - name: install bandit
            run: pip install bandit

          - name: run the bandit scan - static code analysis
            run: bandit -ll -ii -r . -f json -o bandit-report.json

          - name: uploading the artifact
            uses: actions/upload-artifact@v3
            if: always()
            with:
              name: bandit-findings
              path: bandit-report.json

          - name: Check for changes in Capstone-Project-work
            id: changes
            run: |
              if git diff --quiet HEAD^ HEAD ./Capstone-Project-work; then
                echo "No changes in Capstone-Project-work, skipping build."
                exit 0
              fi
              echo "Changes detected in Capstone-Project-work, proceeding with build."

          -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v2
          -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
          -
            name: Login to Docker Hub
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          -
            name: Build and push
            uses: docker/build-push-action@v4
            with:
              context: ./Capstone-Project-work/cap2
              platforms: linux/amd64,linux/arm64
              push: true
              tags: badejotobi/usu:0.${{ github.run_number }}
  ARGO_CD_DEPLOYMENT:
        needs: Build-Push-Docker
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
            name: changing the deployment of git repo
            with:
              repository: 'badejotobi/k8s'
              token: ${{ secrets.GIT_PASSWORD }}
          - name: modify the image
            run: |
              git config user.email badejotobi@gmail.com
              git config user.name badejotobi
              cd usu
              sed -i "s+badejotobi/usu.*+badejotobi/usu:0.$RUN_NUMBER+g" deployment.yaml
              git add .
              git commit -m 'Done  by Github Actions   Job changemanifest: ${{ github.run_number }}'
              git push origin main
            env:
              GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
              GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
              RUN_NUMBER: ${{ github.run_number }}
